"""Add more_images field to Product model

Revision ID: 1b72943d7a73
Revises: d4891c8f00e0
Create Date: 2025-02-28 16:21:35.213622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b72943d7a73'
down_revision = 'd4891c8f00e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('more_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('more_images')

    # ### end Alembic commands ###
